// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_zqJGSF4-Fl_NvZA6XwM3J2DKMZQaeyY',
    appId: '1:447619662142:web:477f6123e49b44546cec6f',
    messagingSenderId: '447619662142',
    projectId: 'farmdirect-6246f',
    authDomain: 'farmdirect-6246f.firebaseapp.com',
    storageBucket: 'farmdirect-6246f.firebasestorage.app',
    measurementId: 'G-785JVSXSCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFABKEpG_7_VnKfgOWLJsgO7XfDxSOIO0',
    appId: '1:447619662142:android:e9a9059ec7bad1276cec6f',
    messagingSenderId: '447619662142',
    projectId: 'farmdirect-6246f',
    storageBucket: 'farmdirect-6246f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZCfRpYvL7_9npEHtDdVIHeDhjDXwHo8',
    appId: '1:447619662142:ios:514e4eabe6c990fe6cec6f',
    messagingSenderId: '447619662142',
    projectId: 'farmdirect-6246f',
    storageBucket: 'farmdirect-6246f.firebasestorage.app',
    iosBundleId: 'com.farmdirect.farmDirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtZCfRpYvL7_9npEHtDdVIHeDhjDXwHo8',
    appId: '1:447619662142:ios:514e4eabe6c990fe6cec6f',
    messagingSenderId: '447619662142',
    projectId: 'farmdirect-6246f',
    storageBucket: 'farmdirect-6246f.firebasestorage.app',
    iosBundleId: 'com.farmdirect.farmDirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_zqJGSF4-Fl_NvZA6XwM3J2DKMZQaeyY',
    appId: '1:447619662142:web:41fb7163a48c80316cec6f',
    messagingSenderId: '447619662142',
    projectId: 'farmdirect-6246f',
    authDomain: 'farmdirect-6246f.firebaseapp.com',
    storageBucket: 'farmdirect-6246f.firebasestorage.app',
    measurementId: 'G-WCQXS7WBEX',
  );

}